module.exports = {

    GET_ACTIVE_LABOR_TICKETS: `
    SELECT ISNULL(LAB.WORKORDER_BASE_ID,'Indirect Labor') AS WORK_ORDER, LAB.INDIRECT_ID, LAB.WORKORDER_BASE_ID, LAB.CLOCK_IN, LAB.RESOURCE_ID, (GETDATE()-LAB.CLOCK_IN) AS DURATION, 
    (EMP.FIRST_NAME + ' ' + EMP.LAST_NAME) AS NAME, EMP.ID,
    WO.PART_ID, WO.DESIRED_WANT_DATE, SR.DESCRIPTION
    FROM PSI.DBO.LABOR_TICKET LAB
    INNER JOIN PSI.DBO.EMPLOYEE EMP ON EMP.ID = LAB.EMPLOYEE_ID
    LEFT JOIN PSI.DBO.WORK_ORDER WO ON WO.BASE_ID = LAB.WORKORDER_BASE_ID AND WO.LOT_ID = LAB.WORKORDER_LOT_ID AND WO.SPLIT_ID = LAB.WORKORDER_SPLIT_ID AND WO.SUB_ID = LAB.WORKORDER_SUB_ID
    LEFT JOIN SHOP_RESOURCE SR ON SR.ID = LAB.RESOURCE_ID
    WHERE HOURS_WORKED IS NULL AND LAB.EMPLOYEE_ID != 'RR' AND EMP.ACTIVE = 'Y'
    ORDER BY LAB.INDIRECT_ID DESC
`
}