module.exports = {

    PRODUCTION_PLANNING_PER_SHOP_RESOURCE: `
    SELECT OP.WORKORDER_BASE_ID, WO.PART_ID, OP.SEQUENCE_NO, OP.RESOURCE_ID, SHOP.DESCRIPTION ,OP.RUN_HRS,
		WO.DESIRED_WANT_DATE, WO.STATUS AS [WO_STATUS], OP.STATUS AS [OP_STATUS], DSL.DEMAND_BASE_ID, DSL.DEMAND_SEQ_NO, WO.DESIRED_QTY, WO.SITE_ID, 
		(SELECT Distinct ',' +  R.PART_ID
			FROM REQUIREMENT R
			LEFT JOIN PART_SITE PS ON PS.PART_ID = R.PART_ID
			WHERE R.STATUS IN ('R','F') AND R.WORKORDER_TYPE= 'W' AND ((R.CALC_QTY - R.ISSUED_QTY) > PS.QTY_ON_HAND ) 
			AND R.WORKORDER_BASE_ID = OP.WORKORDER_BASE_ID AND R.WORKORDER_LOT_ID = OP.WORKORDER_LOT_ID AND R.WORKORDER_SPLIT_ID = OP.WORKORDER_SPLIT_ID AND R.WORKORDER_SUB_ID = OP.WORKORDER_SUB_ID 
			AND R.OPERATION_SEQ_NO = OP.SEQUENCE_NO FOR XML PATH('')) AS [SHORT_PARTS]
        FROM OPERATION OP
        INNER JOIN WORK_ORDER WO ON WO.BASE_ID = OP.WORKORDER_BASE_ID AND WO.LOT_ID = OP.WORKORDER_LOT_ID AND WO.SPLIT_ID = OP.WORKORDER_SPLIT_ID AND WO.SUB_ID = OP.WORKORDER_SUB_ID
        LEFT JOIN DEMAND_SUPPLY_LINK DSL ON DSL.SUPPLY_BASE_ID = WO.BASE_ID AND DSL.SUPPLY_LOT_ID = WO.LOT_ID AND DSL.SUPPLY_SPLIT_ID = WO.SPLIT_ID AND DSL.SUPPLY_SUB_ID = WO.SUB_ID
        LEFT JOIN SHOP_RESOURCE SHOP ON SHOP.ID = OP.RESOURCE_ID
        WHERE OP.WORKORDER_TYPE = 'W' AND WO.STATUS IN ('R', 'F') AND OP.RESOURCE_ID = @RESOURCE_ID

        `,

    PRODUCTION_PLANNING_ALL_SHOP_RESOURCES: `
    SELECT OP.WORKORDER_BASE_ID, WO.PART_ID, OP.SEQUENCE_NO, OP.RESOURCE_ID, SHOP.DESCRIPTION ,OP.RUN_HRS,
    WO.DESIRED_WANT_DATE, WO.STATUS AS [WO_STATUS], OP.STATUS AS [OP_STATUS], DSL.DEMAND_BASE_ID, DSL.DEMAND_SEQ_NO, WO.DESIRED_QTY, WO.SITE_ID,  
    (SELECT Distinct ',' +  R.PART_ID
        FROM REQUIREMENT R
            LEFT JOIN PART_SITE PS ON PS.PART_ID = R.PART_ID
            WHERE R.STATUS IN ('R','F') AND R.WORKORDER_TYPE= 'W' AND ((R.CALC_QTY - R.ISSUED_QTY) > PS.QTY_ON_HAND ) 
            AND R.WORKORDER_BASE_ID = OP.WORKORDER_BASE_ID AND R.WORKORDER_LOT_ID = OP.WORKORDER_LOT_ID AND R.WORKORDER_SPLIT_ID = OP.WORKORDER_SPLIT_ID AND R.WORKORDER_SUB_ID = OP.WORKORDER_SUB_ID 
            AND R.OPERATION_SEQ_NO = OP.SEQUENCE_NO FOR XML PATH('')) AS [SHORT_PARTS]
        FROM OPERATION OP
        INNER JOIN WORK_ORDER WO ON WO.BASE_ID = OP.WORKORDER_BASE_ID AND WO.LOT_ID = OP.WORKORDER_LOT_ID AND WO.SPLIT_ID = OP.WORKORDER_SPLIT_ID AND WO.SUB_ID = OP.WORKORDER_SUB_ID
        LEFT JOIN DEMAND_SUPPLY_LINK DSL ON DSL.SUPPLY_BASE_ID = WO.BASE_ID AND DSL.SUPPLY_LOT_ID = WO.LOT_ID AND DSL.SUPPLY_SPLIT_ID = WO.SPLIT_ID AND DSL.SUPPLY_SUB_ID = WO.SUB_ID
        LEFT JOIN SHOP_RESOURCE SHOP ON SHOP.ID = OP.RESOURCE_ID
        WHERE OP.WORKORDER_TYPE = 'W' AND WO.STATUS IN ('R', 'F')

    `,


    GET_PACKSLIPS_VALUE_BASED_ON_CURRENT_MONTH: ` 
    SELECT SUM((CO.SELL_RATE * SL.USER_SHIPPED_QTY * UNIT_PRICE)) AS AMOUNT,
    DATEPART(DAY, SHIPPED_DATE) AS name
    FROM PSI.DBO.SHIPPER SHIP
    INNER JOIN PSI.DBO.SHIPPER_LINE SL ON SL.PACKLIST_ID=SHIP.PACKLIST_ID
    INNER JOIN PSI.DBO.CUSTOMER_ORDER CO ON CO.ID = SL.CUST_ORDER_ID
    WHERE DATEPART(YEAR, SHIPPED_DATE) = YEAR(GETDATE()) AND DATEPART(MONTH, SHIPPED_DATE) = MONTH(GETDATE())
    GROUP BY DATEPART(DAY, SHIPPED_DATE)
    ORDER BY DATEPART(DAY, SHIPPED_DATE)
    `,

    GET_ALL_SHOP_RESOURCES: `SELECT DISTINCT RESOURCE_ID AS [value], DESCRIPTION AS [label]
    FROM OPERATION OP
    INNER JOIN WORK_ORDER WO ON WO.BASE_ID = OP.WORKORDER_BASE_ID AND WO.LOT_ID = OP.WORKORDER_LOT_ID AND WO.SPLIT_ID = OP.WORKORDER_SPLIT_ID AND WO.SUB_ID = OP.WORKORDER_SUB_ID
    LEFT JOIN SHOP_RESOURCE SHOP ON SHOP.ID = OP.RESOURCE_ID
    WHERE OP.WORKORDER_TYPE = 'W' AND WO.STATUS IN ('R', 'F')`,

    PRODUCTION_PLANNING_WO_CURRENT_WEEK: `DECLARE @next_sat date = DATEADD(DAY, 7 - DATEPART(WEEKDAY, GETDATE()), CAST(GETDATE() AS DATE));


    SELECT WO.BASE_ID, WO.SUB_ID, WO.PART_ID, CONVERT(DATE,WO.DESIRED_WANT_DATE) AS DESIRED_WANT_DATE, WO.STATUS,
        DATEPART(ISO_WEEK,GETDATE()) AS CURRENTWEEK,
        DATEPART(ISO_WEEK,WO.DESIRED_WANT_DATE) AS DUE_WEEK,
        CO.CUSTOMER_ID, CAST(COL.DESIRED_SHIP_DATE AS DATE) AS [ORGINAL_CONFIRMED_DATE], CAST(COL.PROMISE_DATE AS DATE) AS [RECONFIRMED_DATE], 
        CAST(COL.PROMISE_DEL_DATE AS DATE) AS [OTTR],
    
         (SELECT SUM(HOURS_WORKED) FROM LABOR_TICKET 
         WHERE WORKORDER_BASE_ID = WO.BASE_ID AND WORKORDER_LOT_ID = WO.LOT_ID AND WORKORDER_SPLIT_ID = WO.SPLIT_ID AND WORKORDER_SUB_ID = WO.SUB_ID) AS [TOTAL_ACT_RUN_HRS],
    
         (SELECT COUNT(*)
            FROM REQUIREMENT R
            LEFT JOIN PART_SITE PS ON PS.PART_ID = R.PART_ID
            WHERE R.STATUS IN ('R','F') AND R.WORKORDER_TYPE= 'W' AND ((R.CALC_QTY - R.ISSUED_QTY) > PS.QTY_ON_HAND ) AND R.WORKORDER_BASE_ID = WO.BASE_ID AND R.WORKORDER_SUB_ID = WO.SUB_ID) AS [SHORTAGE_COUNT],
    
        ( (SELECT SUM(RUN_HRS) AS TOTAL_RUN_HRS
            FROM OPERATION OP
            WHERE WORKORDER_TYPE = 'W' AND WORKORDER_BASE_ID = WO.BASE_ID AND WORKORDER_LOT_ID = WO.LOT_ID AND WORKORDER_SPLIT_ID = WO.SPLIT_ID AND WORKORDER_SUB_ID = WO.SUB_ID )/WO.DESIRED_QTY)*(COL.USER_ORDER_QTY - COL.TOTAL_USR_SHIP_QTY)  AS [TOTAL_EST_RUN_HOURS_REMAIN],
    
        (SELECT Distinct ', ' +  R.PART_ID
            FROM REQUIREMENT R
            LEFT JOIN PART_SITE PS ON PS.PART_ID = R.PART_ID
            WHERE R.STATUS IN ('R','F') AND R.WORKORDER_TYPE= 'W' AND ((R.CALC_QTY - R.ISSUED_QTY) > PS.QTY_ON_HAND ) AND R.WORKORDER_BASE_ID = WO.BASE_ID AND R.WORKORDER_SUB_ID = WO.SUB_ID
            FOR XML PATH('')) AS [SHORT_PARTS],
    
         (SELECT TOP 1 RESOURCE_ID
         FROM LABOR_TICKET LAB
         WHERE LAB.WORKORDER_BASE_ID = WO.BASE_ID AND LAB.WORKORDER_LOT_ID = WO.LOT_ID AND LAB.WORKORDER_SPLIT_ID = WO.SPLIT_ID AND LAB.WORKORDER_SUB_ID = WO.SUB_ID  AND EMPLOYEE_ID != 'RR'
         ORDER BY ROWID DESC) AS LAST_SEEN,
    
        DSL.DEMAND_BASE_ID, DSL.DEMAND_SEQ_NO,
        COL.TOTAL_USR_SHIP_QTY, COL.USER_ORDER_QTY, (COL.USER_ORDER_QTY - COL.TOTAL_USR_SHIP_QTY) AS QTY_LEFT, (COL.USER_ORDER_QTY - COL.TOTAL_USR_SHIP_QTY) * COL.UNIT_PRICE * CO.SELL_RATE AS PRICE
    
        FROM WORK_ORDER WO
        INNER JOIN DEMAND_SUPPLY_LINK DSL ON DSL.SUPPLY_BASE_ID = WO.BASE_ID AND DSL.SUPPLY_LOT_ID = WO.LOT_ID AND DSL.SUPPLY_SPLIT_ID = WO.SPLIT_ID AND DSL.SUPPLY_SUB_ID = WO.SUB_ID
        INNER JOIN CUST_ORDER_LINE COL ON COL.CUST_ORDER_ID = DSL.DEMAND_BASE_ID AND COL.LINE_NO = DSL.DEMAND_SEQ_NO
        INNER JOIN CUSTOMER_ORDER CO ON CO.ID = COL.CUST_ORDER_ID
        WHERE WO.TYPE = 'W' AND WO.STATUS IN ('R','F') AND WO.DESIRED_WANT_DATE <= @next_sat
        ORDER BY WO.DESIRED_WANT_DATE
    `,

    PRODUCTION_PLANNING_WO_PER_WEEK: `SELECT WO.BASE_ID, WO.SUB_ID, WO.PART_ID, CONVERT(DATE,WO.DESIRED_WANT_DATE) AS DESIRED_WANT_DATE, WO.STATUS,
    DATEPART(ISO_WEEK,GETDATE()) AS CURRENTWEEK,
	DATEPART(ISO_WEEK,WO.DESIRED_WANT_DATE) AS DUE_WEEK,
    CO.CUSTOMER_ID, CAST(COL.DESIRED_SHIP_DATE AS DATE) AS [ORGINAL_CONFIRMED_DATE], CAST(COL.PROMISE_DATE AS DATE) AS [RECONFIRMED_DATE], 
	CAST(COL.PROMISE_DEL_DATE AS DATE) AS [OTTR],

	 (SELECT SUM(HOURS_WORKED) FROM LABOR_TICKET 
	 WHERE WORKORDER_BASE_ID = WO.BASE_ID AND WORKORDER_LOT_ID = WO.LOT_ID AND WORKORDER_SPLIT_ID = WO.SPLIT_ID AND WORKORDER_SUB_ID = WO.SUB_ID) AS [TOTAL_ACT_RUN_HRS],

	 (SELECT COUNT(*)
		FROM REQUIREMENT R
		LEFT JOIN PART_SITE PS ON PS.PART_ID = R.PART_ID
		WHERE R.STATUS IN ('R','F') AND R.WORKORDER_TYPE= 'W' AND ((R.CALC_QTY - R.ISSUED_QTY) > PS.QTY_ON_HAND ) AND R.WORKORDER_BASE_ID = WO.BASE_ID AND R.WORKORDER_SUB_ID = WO.SUB_ID) AS [SHORTAGE_COUNT],

	(SELECT Distinct ', ' +  R.PART_ID
		FROM REQUIREMENT R
		LEFT JOIN PART_SITE PS ON PS.PART_ID = R.PART_ID
		WHERE R.STATUS IN ('R','F') AND R.WORKORDER_TYPE= 'W' AND ((R.CALC_QTY - R.ISSUED_QTY) > PS.QTY_ON_HAND ) AND R.WORKORDER_BASE_ID = WO.BASE_ID AND R.WORKORDER_SUB_ID = WO.SUB_ID
		FOR XML PATH('')) AS [SHORT_PARTS],

    ( (SELECT SUM(RUN_HRS) AS TOTAL_RUN_HRS
        FROM OPERATION OP
        WHERE WORKORDER_TYPE = 'W' AND WORKORDER_BASE_ID = WO.BASE_ID AND WORKORDER_LOT_ID = WO.LOT_ID AND WORKORDER_SPLIT_ID = WO.SPLIT_ID AND WORKORDER_SUB_ID = WO.SUB_ID )/WO.DESIRED_QTY)*(COL.USER_ORDER_QTY - COL.TOTAL_USR_SHIP_QTY)  AS [TOTAL_EST_RUN_HOURS_REMAIN], 

     (SELECT TOP 1 RESOURCE_ID
     FROM LABOR_TICKET LAB
     WHERE LAB.WORKORDER_BASE_ID = WO.BASE_ID AND LAB.WORKORDER_LOT_ID = WO.LOT_ID AND LAB.WORKORDER_SPLIT_ID = WO.SPLIT_ID AND LAB.WORKORDER_SUB_ID = WO.SUB_ID  AND EMPLOYEE_ID != 'RR'
     ORDER BY ROWID DESC) AS LAST_SEEN,

    DSL.DEMAND_BASE_ID, DSL.DEMAND_SEQ_NO,
    COL.TOTAL_USR_SHIP_QTY, COL.USER_ORDER_QTY, (COL.USER_ORDER_QTY - COL.TOTAL_USR_SHIP_QTY) AS QTY_LEFT, (COL.USER_ORDER_QTY - COL.TOTAL_USR_SHIP_QTY) * COL.UNIT_PRICE * CO.SELL_RATE AS PRICE

    FROM WORK_ORDER WO
    INNER JOIN DEMAND_SUPPLY_LINK DSL ON DSL.SUPPLY_BASE_ID = WO.BASE_ID AND DSL.SUPPLY_LOT_ID = WO.LOT_ID AND DSL.SUPPLY_SPLIT_ID = WO.SPLIT_ID AND DSL.SUPPLY_SUB_ID = WO.SUB_ID
    INNER JOIN CUST_ORDER_LINE COL ON COL.CUST_ORDER_ID = DSL.DEMAND_BASE_ID AND COL.LINE_NO = DSL.DEMAND_SEQ_NO
    INNER JOIN CUSTOMER_ORDER CO ON CO.ID = COL.CUST_ORDER_ID
    WHERE WO.TYPE = 'W' AND WO.STATUS IN ('R','F', 'C') AND CO.STATUS IN ('R','F', 'C') AND DATEPART(ISO_WEEK,WO.DESIRED_WANT_DATE) = @WEEK_NO AND YEAR(WO.DESIRED_WANT_DATE) = YEAR(GETDATE())
	ORDER BY WO.DESIRED_WANT_DATE`,


    PRODUCTION_PLANNING_DATE_VALIDATION : `SELECT CO.ID, CO.CUSTOMER_ID,
    COL.LINE_NO, COL.PART_ID, CAST(COL.DESIRED_SHIP_DATE AS DATE) AS [ORGINAL_CONFIRMED_DATE], CAST(COL.PROMISE_DATE AS DATE) AS [RECONFIRMED_DATE], 
    CAST(COL.PROMISE_DEL_DATE AS DATE) AS [NEED_DATE_OTTR], WO.STATUS,
    DSL.SUPPLY_BASE_ID, WO.SUB_ID, CAST(WO.DESIRED_WANT_DATE AS DATE) AS [WO_WANT_DATE],
    CASE
    WHEN (DATEPART(YEAR,WO.DESIRED_WANT_DATE) = 2022 AND WO.STATUS IN ('R','F')) THEN DATEPART(WEEK,WO.DESIRED_WANT_DATE)
    WHEN (DATEPART(YEAR,WO.DESIRED_WANT_DATE) = 2022 AND WO.STATUS IN ('C')) THEN DATEPART(WEEK,WO.DESIRED_WANT_DATE)
    WHEN (DATEPART(YEAR,WO.DESIRED_WANT_DATE) = 2021 AND WO.STATUS IN ('R','F'))  THEN DATEPART(WEEK, GETDATE())
    WHEN (DATEPART(YEAR,WO.DESIRED_WANT_DATE) = 2021 AND WO.STATUS IN ('C')) THEN -1
    ELSE -2
    END AS [WEEK],
    CASE
        WHEN (ISNULL(COL.PROMISE_DATE, COL.DESIRED_SHIP_DATE) = CAST(WO.DESIRED_WANT_DATE+2 AS DATE)) THEN 1 --CUSTOMER NOTIFIED ALL GOOD
        WHEN (ISNULL(COL.PROMISE_DATE, COL.DESIRED_SHIP_DATE) = WO.DESIRED_WANT_DATE) THEN 2   --UPDATE DATE (-2)
        WHEN (COL.PROMISE_DATE IS NULL AND COL.DESIRED_SHIP_DATE IS NULL AND COL.PROMISE_DEL_DATE IS NULL) THEN 3  --RED ALERT ALL DATES MISSING
        WHEN (COL.PROMISE_DATE IS NULL AND COL.DESIRED_SHIP_DATE IS NULL) THEN 3    --RED ALERT DATES MISSING
        WHEN (ISNULL(COL.PROMISE_DATE, COL.DESIRED_SHIP_DATE) < CAST(WO.DESIRED_WANT_DATE-5 AS DATE)) THEN 4  -- ATTENTION SALES
        WHEN (ISNULL(COL.PROMISE_DATE, COL.DESIRED_SHIP_DATE) > CAST(WO.DESIRED_WANT_DATE-5 AS DATE)) THEN 5  -- ATTENTION PROD
    ELSE 0
    END AS [CHECK]

    FROM CUSTOMER_ORDER CO 
    INNER JOIN CUST_ORDER_LINE COL ON CO.ID = COL.CUST_ORDER_ID
    LEFT OUTER JOIN DEMAND_SUPPLY_LINK DSL ON COL.CUST_ORDER_ID = DSL.DEMAND_BASE_ID AND COL.LINE_NO = DSL.DEMAND_SEQ_NO
    LEFT OUTER JOIN WORK_ORDER WO ON WO.BASE_ID = DSL.SUPPLY_BASE_ID AND WO.LOT_ID = DSL.SUPPLY_LOT_ID AND WO.SPLIT_ID = DSL.SUPPLY_SPLIT_ID AND WO.SUB_ID = DSL.SUPPLY_SUB_ID
    WHERE CO.STATUS IN ('R','F') AND SUPPLY_BASE_ID IS NOT NULL AND WO.STATUS IN ('R','F') --AND WO.BASE_ID = '47501'
    ORDER BY WO_WANT_DATE`,

    UPDATE_WORKORDER_WANT_DATE: `
    UPDATE WORK_ORDER
    SET DESIRED_WANT_DATE = @WO_DATE
    WHERE BASE_ID = @WO AND SUB_ID = 0
    `

}